crm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dealdesk-crm/urls.py
"""
URL configuration for dealdesk-crm project.
"""
from django.contrib import admin
from django.urls import path, include
from dashboard.views import DashboardView
from landing.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    # URLs for the apps
    path('', include('landing.urls', namespace='landing')),
    path('dashboard/', include('dashboard.urls')),
    path('lead_master/', include('lead_master.urls', namespace='lead_master')),
    path('client/', include('client.urls', namespace='client')),
    path(
        'task_manager/',
        include(
            'task_manager.urls',
            namespace='task_manager')),

    # Authentication URLs from allauth
    path('accounts/', include('allauth.urls')),
]

task_manager/urls.py
from django.urls import path
from .views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView

app_name = 'task_manager'

urlpatterns = [
    path('list/', TaskListView.as_view(), name='task_list'),
    path('new/', TaskCreateView.as_view(), name='task_new'),
    path('edit/<int:pk>/', TaskUpdateView.as_view(), name='task_edit'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
]

task_manager/models.py
from django.db import models
from django.contrib.auth.models import User


def get_salesman():
    """
    Get the default ID for the salesman.
    """
    return 2


STATUS_CHOICES = [
    ("TBD", "To Do"),
    ("D", "Done"),
]

PRIORITY_CHOICES = [
    ("N", "Normal"),
    ("U", "Urgent"),
]


class TaskManager(models.Model):
    """
    Represents a task manager model.
    """
    title = models.CharField(max_length=55, null=False)
    description = models.CharField(max_length=255)
    due_date = models.DateField(null=False)
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default="To Do",
        null=False
    )
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOICES,
        default="Normal",
        null=False
    )
    assigned_to = models.ForeignKey(
        'team.Sar',
        on_delete=models.SET(get_salesman),
        related_name='tasks'
    )

    class Meta:
        """
        Meta options for the TaskManager model.
        """
        ordering = ['due_date']

    def __str__(self):
        return self.title

task_manager/forms.py
from django import forms
from django.forms import DateInput
from .models import TaskManager, STATUS_CHOICES, PRIORITY_CHOICES
from team.models import Sar


class TaskManagerFilterForm(forms.Form):
    """
    Filter form for filtering task managers.
    """
    assigned_to = forms.ModelChoiceField(
        queryset=Sar.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('', 'All')] + STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    priority = forms.ChoiceField(
        choices=[('', 'All')] + PRIORITY_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )


class TaskManagerForm(forms.ModelForm):
    """
    Form for creating and updating task manager information.
    """
    class Meta:
        model = TaskManager
        fields = '__all__'
        labels = {
            'title': 'Title',
            'description': 'Description',
            'due_date': 'Due Date',
            'status': 'Status',
            'priority': 'Priority',
            'assigned_to': 'Assigned To',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                    'tabindex': '1'}),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control form-control-lg',
                    'rows': '3',
                    'style': 'font-size: 16px',
                    'placeholder': 'Description',
                    'tabindex': '2'}),
            'due_date': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                            'tabindex': '3'}),
            'status': forms.Select(
                attrs={
                    'class': 'form-control',
                    'tabindex': '4'}),
            'priority': forms.Select(
                attrs={
                    'class': 'form-control',
                    'tabindex': '5'}),
            'assigned_to': forms.Select(
                attrs={
                    'class': 'form-control',
                    'tabindex': '6'}),
        }

    def __init__(self, *args, **kwargs):
        """
        Initialize the form and set the queryset for the 'assigned_to' field.
        """
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].queryset = Sar.objects.all()

task_manager/views.py
from django.shortcuts import render, get_list_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import TaskManager
from .forms import TaskManagerFilterForm, TaskManagerForm


class TaskListView(ListView):
    """
    View class for listing tasks.
    """
    model = TaskManager
    template_name = 'task_manager/task_list.html'
    context_object_name = 'tasks'
    paginate_by = 10

    def get_queryset(self):
        """
        Get the queryset of tasks based on the filter parameters.
        """
        queryset = super().get_queryset()
        form = TaskManagerFilterForm(self.request.GET)
        if form.is_valid():
            status = form.cleaned_data['status']
            priority = form.cleaned_data['priority']
            assigned_to = form.cleaned_data['assigned_to']
            if status:
                queryset = queryset.filter(status=status)
            if priority:
                queryset = queryset.filter(priority=priority)
            if assigned_to:
                queryset = queryset.filter(assigned_to=assigned_to)
        return queryset

    def get_context_data(self, **kwargs):
        """
        Add context data for rendering the template.
        """
        context = super().get_context_data(**kwargs)
        context['filter_form'] = TaskManagerFilterForm(self.request.GET)
        context['task'] = TaskManager.objects.first()
        return context


class TaskCreateView(CreateView):
    """
    View class for creating a new task.
    """
    model = TaskManager
    form_class = TaskManagerForm
    template_name = 'task_manager/task_create.html'
    success_url = reverse_lazy('task_manager:task_list')

    def form_invalid(self, form):
        """
        Handle form validation errors and add styling to invalid fields.
        """
        for field in form.errors:
            form[field].field.widget.attrs['class'] += ' is-invalid'
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        """
        Handle form validation when the form is valid.
        """
        return super().form_valid(form)


class TaskUpdateView(UpdateView):
    """
    View class for updating a task.
    """
    model = TaskManager
    form_class = TaskManagerForm
    template_name = 'task_manager/task_edit.html'
    success_url = reverse_lazy('task_manager:task_list')

    def form_invalid(self, form):
        """
        Handle form validation errors and add styling to invalid fields.
        """
        for field in form.errors:
            form[field].field.widget.attrs['class'] += ' is-invalid'
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        """
        Handle form validation when the form is valid.
        """
        return super().form_valid(form)


class TaskDeleteView(DeleteView):
    """
    View class for deleting a task.
    """
    model = TaskManager
    template_name = 'task_manager/task_delete.html'
    success_url = reverse_lazy('task_manager:task_list')

task_manager/templates/task_manager/task_confirm_delete_modal.html
<!-- Delete confirmation modal -->
<div id="confirmDeleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this task?</p>
            </div>
            <div class="modal-footer">
                <form method="post" action="{% url 'task_manager:task_delete' pk=task.pk %}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" name="confirm" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

task_manager/templates/task_manager/task_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-lg-12">
  <div class="row">
    <div class="col-12">
      <h3 class="bg-body">Create a new Task</h3>

      <!-- Create a new task -->
      <div class="container mt-4">
        <form method="post" action="{% url 'task_manager:task_new' %}">
          {% csrf_token %}
          <div class="row">
            {% for field in form %}
            <div class="col-12">
              <div class="form-group">
                <div class="input-group">
                  {{ field|as_crispy_field }}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="form-group">
            <!-- Save button -->
            <button type="submit" class="btn btn-primary">Save</button>
            <!-- Cancel button -->
            <a href="{% url 'task_manager:task_list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/task_manager/task_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-lg-12">
  <div class="row">
    <div class="col-12">
      <h3 class="bg-body">Edit {{ task.title }} Task Details</h3>

      <!-- Edit an existing task -->
      <div class="container mt-4">
        <form method="post">
          {% csrf_token %}
          <div class="row">
            {% for field in form %}
            <div class="col-12">
              <div class="form-group">
                <div class="input-group">
                  {{ field|as_crispy_field }}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="form-group">

            <!-- Save button -->
            <button type="submit" class="btn btn-primary">Save</button>
            <!-- Cancel button -->
            <a href="{% url 'task_manager:task_list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/task_manager/task_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <h3 class="bg-body">Task List</h3>

            <!-- Filter Form -->
            <form class="mb-3" method="get" action="{% url 'task_manager:task_list' %}">
                {% csrf_token %}
                <div class="container mt-5">
                    <div class="row">
                        {% for field in filter_form %}
                        <div class="col-lg-4 col-md-6 col-sm-12">
                            <div class="form-group">
                                {{ field|as_crispy_field }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-secondary">Apply</button>
                    </div>
                </div>
            </form>

            <!-- Add task button -->
            <div class="d-flex justify-content-end">
                <a href="{% url 'task_manager:task_new' %}"
                    class="btn btn-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                    Add
                </a>
            </div>

            <!-- Task List -->
            <div class="container mt-5">
                <div class="container table-responsive overflow-x-scroll">
                  <table class="table bg-body-tertiary table-hover">
                        
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Due Date</th>
                                    <th>Status</th>
                                    <th>Priority</th>
                                    <th>Assigned To</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for task in tasks %}
                                <tr>
                                    <td>{{ task.title }}</td>
                                    <td>{{ task.description }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>{{ task.get_status_display }}</td>
                                    <td>{{ task.get_priority_display }}</td>
                                    <td>{{ task.assigned_to }}</td>
                                    <td>
                                        <!-- Task edit button -->
                                        <button type="button"
                                            onclick="location.href='{% url 'task_manager:task_edit' pk=task.pk %}'"
                                            class="btn btn-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                            Edit
                                        </button>
                                    </td>
                                    <td>
                                        <!-- Delete Button -->
                                        <button class="btn btn-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                                            data-bs-toggle="modal"
                                            data-bs-target="#confirmDeleteModal">Delete</button>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="6">No tasks found.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Pagination -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

<!-- Task Delete Confirmation Modal -->
{% include 'task_manager/task_confirm_delete_modal.html' %}
{% endblock %}