client/urls.py
from django.urls import path
from .views import (
    ClientListView,
    ClientCreateView,
    ClientUpdateView,
    ClientDetailView,
    ClientDeleteView,
)


app_name = 'client'

urlpatterns = [
    path('list/', ClientListView.as_view(), name='client_list'),
    path('new/', ClientCreateView.as_view(), name='client_new'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),
    path('detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dealdesk-crm/urls.py
"""
URL configuration for dealdesk-crm project.
"""
from django.contrib import admin
from django.urls import path, include
from dashboard.views import DashboardView
from landing.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    # URLs for the apps
    path('', include('landing.urls', namespace='landing')),
    path('dashboard/', include('dashboard.urls')),
    path('lead_master/', include('lead_master.urls', namespace='lead_master')),
    path('client/', include('client.urls', namespace='client')),
    path(
        'task_manager/',
        include(
            'task_manager.urls',
            namespace='task_manager')),

    # Authentication URLs from allauth
    path('accounts/', include('allauth.urls')),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils import timezone
from team.models import Sar, Manager


#  Get a default ID
def get_manager():
    return 2


def get_salesman():
    return 2


CLIENT_TYPE_CHOICES = [
    ("ARC", "Architect"),
    ("PLM", "Plumbing Contractor"),
    ("DVP", "Developer"),
    ("EPC", "EPC Contractor"),
    ("CLN", "End-Client"),
]


class Client(models.Model):
    """
    Represents a client in the system.
    """
    company_name = models.CharField(max_length=255, null=False)
    first_name = models.CharField(max_length=55, null=False)
    last_name = models.CharField(max_length=55, null=False)
    client_type = models.CharField(
        max_length=55,
        choices=CLIENT_TYPE_CHOICES,
        null=False,
        default="CLN"
    )
    address1 = models.CharField(max_length=255, null=False)
    address2 = models.CharField(max_length=255, null=False)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=255, null=False)
    country = models.CharField(max_length=255)
    telephone = models.CharField(max_length=20)
    mobile = models.CharField(max_length=20, null=False)
    email = models.EmailField(null=False)
    salesman = models.ForeignKey(
        Sar,
        on_delete=models.SET(get_salesman),
        # null=True,  # Set the foreign key field as nullable
        # blank=False,  # Doesn't allow the foreign key field to be empty in
        # forms,
        related_name='clients'
    )
    manager = models.ForeignKey(
        Manager,
        on_delete=models.SET(get_manager),
        related_name='clients'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        """
        Metadata options for the Client model.
        """
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        db_table = 'Client.Client'
        ordering = ['company_name']

    def __str__(self):
        return self.company_name

client/forms.py
from django import forms
from .models import Client, CLIENT_TYPE_CHOICES
from team.models import Sar


class ClientFilterForm(forms.Form):
    """
    Filter form for filtering clients
    """
    client_type = forms.ChoiceField(
        choices=[('', 'All')] + list(CLIENT_TYPE_CHOICES),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    salesman = forms.ModelChoiceField(
        queryset=Sar.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )

    search_keyword = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )


class ClientForm(forms.ModelForm):
    """
    Form for creating and updating client information.
    """
    class Meta:
        model = Client
        fields = '__all__'
        labels = {
            'company_name': 'Company Name',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'client_type': 'Client Type',
            'address1': 'Address Line 1',
            'address2': 'Address Line 2',
            'postal_code': 'Postal Code',
            'city': 'City',
            'country': 'Country',
            'telephone': 'Telephone',
            'mobile': 'Mobile',
            'email': 'Email',
            'salesman': 'Salesman',
            'manager': 'Manager',
        }
        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Company Name', 'tabindex': '1'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'tabindex': '2'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name', 'tabindex': '3'}),
            'client_type': forms.Select(attrs={'class': 'form-control', 'tabindex': '4'}),
            'address1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address Line 1', 'tabindex': '5'}),
            'address2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address Line 2', 'tabindex': '6'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Postal Code', 'tabindex': '7'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City', 'tabindex': '8'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country', 'tabindex': '8'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+46 123 456 789', 'tabindex': '9'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+46 123 456 789', 'tabindex': '10'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'name@example.com', 'tabindex': '11'}),
            'salesman': forms.Select(attrs={'class': 'form-control', 'tabindex': '12'}),
            'manager': forms.Select(attrs={'class': 'form-control', 'tabindex': '13'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

client/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView
)
from django.db import IntegrityError, transaction
from .models import Client
from .forms import ClientForm, ClientFilterForm


class ClientListView(ListView):
    """
    Display a list of clients.
    """
    model = Client
    template_name = 'client/client_list.html'
    context_object_name = 'clients'
    paginate_by = 10

    def get_queryset(self):
        """
        Get the queryset of clients with applied filters.
        """
        queryset = super().get_queryset()
        client_type = self.request.GET.get('client_type')
        salesman = self.request.GET.get('salesman')
        search_keyword = self.request.GET.get('search_keyword')

        if client_type:
            queryset = queryset.filter(client_type=client_type)

        if salesman:
            queryset = queryset.filter(salesman_id=salesman)

        if search_keyword:
            queryset = queryset.filter(
                Q(company_name__icontains=search_keyword) |
                Q(first_name__icontains=search_keyword) |
                Q(last_name__icontains=search_keyword) |
                Q(city__icontains=search_keyword) |
                Q(country__icontains=search_keyword)
            )

        return queryset

    def get_context_data(self, **kwargs):
        """
        Add context data for rendering the template.
        """
        context = super().get_context_data(**kwargs)
        context['filter_form'] = ClientFilterForm(self.request.GET)
        context['client_form'] = ClientForm()
        return context

    def post(self, request, *args, **kwargs):
        """
        Handle form submission via POST request.
        """
        client_form = ClientForm(request.POST)
        if client_form.is_valid():
            client_form.save()
            return redirect('client:client_list')
        else:
            filter_form = ClientFilterForm(request.GET)
            return render(request, self.template_name, {
                'clients': self.get_queryset(),
                'filter_form': filter_form,
                'client_form': client_form,
            })


class ClientCreateView(CreateView):
    """
    Create a new client.
    """
    model = Client
    template_name = "client/client_create.html"
    form_class = ClientForm
    success_url = reverse_lazy('client:client_list')

    def form_invalid(self, form):
        """
        Handle invalid form submission.
        """
        for field in form.errors:
            form[field].field.widget.attrs['class'] += ' is-invalid'
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        """
        Handle valid form submission.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    """
    Update an existing client.
    """
    model = Client
    template_name = "client/client_edit.html"
    form_class = ClientForm

    def get_success_url(self):
        """
        Get the success URL after updating the client.
        """
        client = self.get_object()
        return reverse('client:client_detail', kwargs={'pk': client.pk})

    def form_invalid(self, form):
        """
        Handle invalid form submission.
        """
        for field in form.errors:
            form[field].field.widget.attrs['class'] += ' is-invalid'
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        """
        Handle valid form submission.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)


class ClientDetailView(DetailView):
    """
    Display details of a client.
    """
    model = Client
    template_name = 'client/client_detail.html'
    context_object_name = 'client'

    def get_object(self, queryset=None):
        """
        Retrieve the client object or return a 404 response if not found.
        """
        pk = self.kwargs.get('pk')
        return get_object_or_404(Client, pk=pk)


class ClientDeleteView(DeleteView):
    """
    Delete a client.
    """
    model = Client
    template_name = 'client/client_delete.html'
    success_url = reverse_lazy('client:client_list')

client/templates/client/client_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <h3 class="bg-body">Create a new Lead</h3>

      <!-- Create a new lead -->
      <div class="container mt-4">
        <form class="form-floating" method="post" action="{% url 'client:client_new' %}">
          {% csrf_token %}

          <div class="row">
            {% for field in form %}
            <div class="col-lg-4 col-md-6 col-sm-12">
              {{ field|as_crispy_field }}
            </div>
            {% endfor %}
          </div>

          <!-- Save button -->
          <button type="submit" class="btn btn-primary">Save</button>

          <!-- Cancel button -->
          <a href="{% url 'client:client_list' %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-12">
  <div class="row">
    <div class="col-12">
      <!-- Heading Container -->
      <div class="container mt-5">
        <div class="row col-12">
          <h3 class="bg-body">Client Details: {{ client.company_name }}</h3>
        </div>
      </div>
      <div class="container mt-4">
        <div class="card">
          <div class="card-body">
            <!-- Table -->
            <table class="table">
              <tbody>
                <tr>
                  <th>Company Name:</th>
                  <td>{{ client.company_name }}</td>
                </tr>
                <tr>
                  <th>First Name:</th>
                  <td>{{ client.first_name }}</td>
                </tr>
                <tr>
                  <th>Last Name:</th>
                  <td>{{ client.last_name }}</td>
                </tr>
                <tr>
                  <th>Client Type:</th>
                  <td>{{ client.get_client_type_display }}</td>
                </tr>
                <tr>
                  <th>Address Line 1:</th>
                  <td>{{ client.address1 }}</td>
                </tr>
                <tr>
                  <th>Address Line 2:</th>
                  <td>{{ client.address2 }}</td>
                </tr>
                <tr>
                  <th>Postal Code:</th>
                  <td>{{ client.postal_code }}</td>
                </tr>
                <tr>
                  <th>City:</th>
                  <td>{{ client.city }}</td>
                </tr>
                <tr>
                  <th>Country:</th>
                  <td>{{ client.country }}</td>
                </tr>
                <tr>
                  <th>Telephone:</th>
                  <td>{{ client.telephone }}</td>
                </tr>
                <tr>
                  <th>Mobile:</th>
                  <td>{{ client.mobile }}</td>
                </tr>
                <tr>
                  <th>Email:</th>
                  <td>{{ client.email }}</td>
                </tr>
                <tr>
                  <th>Salesman:</th>
                  <td>{{ client.salesman }}</td>
                </tr>
                <tr>
                  <th>Manager:</th>
                  <td>{{ client.manager }}</td>
                </tr>
                <tr>
                  <th>Created On:</th>
                  <td>{{ client.created_on }}</td>
                </tr>
                <tr>
                  <th>Updated On:</th>
                  <td>{{ client.updated_on }}</td>
                </tr>
              </tbody>
            </table>

            <!-- Edit button -->
            <button type="button" onclick="location.href='{% url 'client:client_edit' client.pk %}'"
              class="btn btn-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
              data-bs-toggle="tooltip" data-bs-placement="bottom" title="Update client details">
              Edit
            </button>

            <!-- Delete Button -->
            <button class="btn btn-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
              data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">Delete</button>

            <!-- Back to client list button -->
            <button type="button" onclick="location.href='{% url 'client:client_list' %}'"
              class="btn btn-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
              Back to Client List
            </button>
          </div>
        </div>
      </div>

      <!-- Client Delete Confirmation Modal -->
      {% include 'client/confirm_delete_modal.html' %}

    </div>
  </div>
</div>
{% endblock %}

client/templates/client/client_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-12 mt-5">
      <h3 class="bg-body ps-4">Edit {{ client.company_name }} Details</h3>

      <!-- Edit an existing client -->
      <div class="container mt-4">
        <form method="post">
          {% csrf_token %}
          <div class="row">
            {% for field in form %}
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="form-group">
                {{ field|as_crispy_field }}
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="form-group">

            <!-- Save button -->
            <button type="submit" class="btn btn-primary">Save</button>
            <!-- Cancel button -->
            <a href="{% url 'client:client_list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-lg-12">
  <div class="row">
    <div class="col-12">
      <!-- Heading Container -->
      <div class="container mt-5">
        <div class="container ms-2">
          <div class="row">
            <div class="col-12">
              <h3 class="bg-body">Client List</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <!-- Filter Form Container -->
        <form method="get" action="{% url 'client:client_list' %}">
          <div class="container mt-5">
            <div class="row">
              <div class="col-sm-4">
                <div class="p-2">
                  {{ filter_form.client_type|as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="p-2">
                  {{ filter_form.salesman|as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="p-2">
                  {{ filter_form.search_keyword|as_crispy_field }}
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-secondary ms-2">Apply</button>
            <!-- View add client button -->
            <div class="d-flex justify-content-end">
              <a href="{% url 'client:client_new' %}"
                class="btn btn-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add a client">
                Add
              </a>
            </div>
          </div>
        </form>
        <!-- Client List Container -->
        <div class="container mt-5">
          <div class="container table-responsive overflow-x-scroll">
            <table class="table bg-body-tertiary table-hover">
              <!-- Table Headers -->
              <thead>
                <tr>
                  <th>Company Name</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Client Type</th>
                  <th>City</th>
                  <th>Country</th>
                  <th>Salesman</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for client in clients %}
                <tr>
                  <td>{{ client.company_name }}</td>
                  <td>{{ client.first_name }}</td>
                  <td>{{ client.last_name }}</td>
                  <td>{{ client.get_client_type_display }}</td>
                  <td>{{ client.city }}</td>
                  <td>{{ client.country }}</td>
                  <td>{{ client.salesman }}</td>
                  <td>
                    <!-- View client details button -->
                    <button type="button" onclick="location.href='{% url 'client:client_detail' pk=client.pk %}'"
                      class="btn btn-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                      Details
                    </button>
                  </td>
                  <td>
                    <!-- View client edit button -->
                    <button type="button" onclick="location.href='{% url 'client:client_edit' pk=client.pk %}'"
                      class="btn btn-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                      Edit
                    </button>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="7">No clients found.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- Pagination -->
          {% if is_paginated %}
          <nav aria-label="Page navigation">
            <ul class="pagination">
              {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
              </li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
              <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
              {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
              {% endif %}
            </ul>
          </nav>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

client/templates/client/confirm_delete_modal.html
<!-- Delete confirmation model -->
<div id="confirmDeleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this client?</p>
            </div>
            <div class="modal-footer">
                <form method="post" action="{% url 'client:client_delete' pk=object.pk %}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" name="confirm" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>