crm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dealdesk-crm/urls.py
"""
URL configuration for dealdesk-crm project.
"""
from django.contrib import admin
from django.urls import path, include
from dashboard.views import DashboardView
from landing.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    # URLs for the apps
    path('', include('landing.urls', namespace='landing')),
    path('dashboard/', include('dashboard.urls')),
    path('lead_master/', include('lead_master.urls', namespace='lead_master')),
    path('client/', include('client.urls', namespace='client')),
    path(
        'task_manager/',
        include(
            'task_manager.urls',
            namespace='task_manager')),

    # Authentication URLs from allauth
    path('accounts/', include('allauth.urls')),
]

landing/urls.py
"""
URL configuration for the landing app.
"""
from django.urls import path
from .views import LandingPageView

app_name = 'landing'

urlpatterns = [
    path('', LandingPageView.as_view(), name='index'),
    # Other URL patterns specific to the landing app
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Links -->
    {% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"
        integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- navbar css -->
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <!-- color mode css -->
    <link rel="stylesheet" href="{% static 'css/color-mode.css' %}">
    {% endblock %}

    <!-- Font Awesome link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Google font link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">

    <!-- Favicon link -->
    <link rel="apple-touch-icon" sizes="180x180" href="https://res.cloudinary.com/pjdevex/image/upload/v1689078033/static/dealdesk-crm/favicons/apple-touch-icon_lpe74m.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://res.cloudinary.com/pjdevex/image/upload/v1689078033/static/dealdesk-crm/favicons/favicon-32x32_uatxin.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://res.cloudinary.com/pjdevex/image/upload/v1689078033/static/dealdesk-crm/favicons/favicon_bf9syx.ico">
    <link rel="manifest" href="https://res.cloudinary.com/pjdevex/raw/upload/v1689078033/static/dealdesk-crm/favicons/site_akzpab.webmanifest">

    <!-- SEO-related meta tags -->
    <meta name="description"
        content="DealDesk - An easy-to-use CRM solution tailored to the specific needs of SMEs. Overcome barriers to adopting CRM systems with DealDesk.">
    <meta name="keywords"
        content="CRM solution, SME CRM, Easy-to-use CRM, Customer experience, Efficiency, Data management, Cloud-based solution, Customer data, Automation, Customer satisfaction, Revenue growth, Informed decision-making">
    <meta name="author" content="PJDEVEX">
    <meta name="robots" content="index, nofollow">

    <!-- Dynamic titles along with the brand name -->
    <title>{% block title %}{% endblock %} | DealDesk CRM</title>
</head>

<body>
    <header class="navbar sticky-top flex-md-nowrap p-0 shadow fixed-top">
        <!-- branding -->
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 rounded-bottom-5"
            href="{% url 'landing:index' %}">
            <div class="card" style="width: 8rem;">
                <img src="https://res.cloudinary.com/pjdevex/image/upload/v1689184170/static/dealdesk_crm_logo/dd_hr_light_qo3739.webp"
                    alt="DealDesk | CRM" class="card-img-top rounded">
            </div>
        </a>

        <!-- Toggle navbar -->
        {% include 'includes/navbar_toggle.html' %}
    </header>

    <div class="container-fluid">
        <div class="row">
            <!-- side navbar -->
            {% include 'includes/navbar.html' %}
            <!-- Main body -->
            <main class="col-md-12 col-lg-10 offset-lg-2 px-md-4">
                {% block content %}

                {% endblock %}
            </main>
        </div>
    </div>

    <!-- Color mode change -->
    <div>
        {% include 'includes/color-mode.html' %}
    </div>

    <!-- Links to script files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <script src="{% static 'script/color-mode.js' %}"></script>
</body>

</html>